site_name: Django GDS Grabbage
site_url: https://uktrade.github.io/django-gds-grabbage/
repo_url: https://github.com/uktrade/django-gds-grabbage/
site_description: Documentation for the Django GDS Grabbage package
plugins:
  - material/social:
      cards_color:
        fill: "#ffffff"
        text: "#000000"
      cards_font: "Roboto"

  - material/search:
      lang: en
  - mkdocstrings:
      handlers:
        python:
          options:
            docstring_style: google

theme:
  name: tech_docs_template
  language: en
  features:
    - navigation.instant
    - navigation.tracking
    - navigation.tabs
    - navigation.indexes
    - navigation.top
    - header.autohide
    - search.suggest
    - search.highlight
    - search.share
  logo: logos/moj.png
  favicon: favicons/moj.ico

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/uktrade/django-gds-grabbage

extra_javascript:
  - https://unpkg.com/tablesort@5.3.0/dist/tablesort.min.js # /PS-IGNORE
  - js/tablesort.js

markdown_extensions:
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.highlight:
      linenums: null
      anchor_linenums: true
      use_pygments: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - tables

nav:
  - "index.md"
  - "getting-started.md"
  - "contributing/index.md"
